select = ["E", "F", "I", "S"]
line-length = 120
target-version = "py311"
unfixable = ["F401", "F841"]
ignore = ["S603", "S607"]

[per-file-ignores]
"__init__.py" = ["F401"]
"tests/test*.py" = ["S101"]
