#!/usr/bin/bash

function start() {
    /seafile/server/seafile-server/seafile.sh stop
    sleep 10
    echo "Running seaf-gc"
    /seafile/server/seafile-server/seaf-gc.sh
}

function end() {
    /seafile/server/seafile-server/seafile.sh start
}

case $1 in
    "start" )
        start;
        ;;
    "end" )
        end;
        ;;
esac
